# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fix_frame_rate": "00_prep.ipynb",
         "chunk_videos": "00_prep.ipynb",
         "get_rand_imgs": "00_prep.ipynb",
         "vid_from_frames": "00_prep.ipynb",
         "gen_vcodebook": "01_features.ipynb",
         "get_df": "01_features.ipynb",
         "get_bovw": "01_features.ipynb",
         "calc_tf_idf": "02_eval.ipynb",
         "cosine_similarity": "02_eval.ipynb"}

modules = ["prep.py",
           "features.py",
           "eval.py"]

git_url = "https://github.com/ncoop57/tango/tree/master/"

def custom_doc_links(name): return None
