# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fix_frame_rate": "00_prep.ipynb",
         "chunk_videos": "00_prep.ipynb",
         "get_rand_imgs": "00_prep.ipynb",
         "vid_from_frames": "00_prep.ipynb",
         "save_detected_frames": "00_prep.ipynb",
         "gen_vids_from_v2s": "00_prep.ipynb",
         "run_phase1_v2s": "00_prep.ipynb",
         "Video": "00_prep.ipynb",
         "VideoDataset": "00_prep.ipynb",
         "Extractor": "03_cnn.ipynb",
         "SIFTExtractor": "01_features.ipynb",
         "CNNExtractor": "01_features.ipynb",
         "gen_vcodebook": "01_features.ipynb",
         "get_df": "01_features.ipynb",
         "get_bovw": "01_features.ipynb",
         "new_get_bovw": "01_features.ipynb",
         "calc_tf_idf": "02_eval.ipynb",
         "cosine_similarity": "02_eval.ipynb",
         "mean_reciprocal_rank": "02_eval.ipynb",
         "r_precision": "02_eval.ipynb",
         "precision_at_k": "02_eval.ipynb",
         "average_precision": "02_eval.ipynb",
         "mean_average_precision": "02_eval.ipynb",
         "evaluate": "02_eval.ipynb",
         "Hook": "03_cnn.ipynb",
         "get_output": "03_cnn.ipynb",
         "get_input": "03_cnn.ipynb",
         "get_named_module_from_model": "03_cnn.ipynb",
         "trainPetsModel": "03_cnn.ipynb",
         "getFeaturesResNet50": "03_cnn.ipynb",
         "trainAsModel": "03_cnn.ipynb",
         "LayeredExtractor": "03_cnn.ipynb",
         "createExtractor": "03_cnn.ipynb",
         "createLayeredExtractor": "03_cnn.ipynb"}

modules = ["prep.py",
           "features.py",
           "eval.py",
           "cnn.py"]

git_url = "https://github.com/ncoop57/tango/tree/master/"

def custom_doc_links(name): return None
