# AUTOGENERATED! DO NOT EDIT! File to edit: dev/05_cli.ipynb (unless otherwise specified).

__all__ = ['tango']

# Cell
import pickle
import pprint

from fastscript import call_parse, Param, bool_arg
from pathlib import Path
from .prep import *
from .features import *
from .eval import *
from .model import *
from .approach import *

# Cell
@call_parse
def tango(
    q_path:Param("Path to the query video", str),
    cor_path:Param("Path to the corpus", str),
    cb_path:Param("Path to the codebook", str),
    vis_path:Param("Path to SimCLR checkpoint", str),
    fps:Param("FPS to set the vidoes to", int) = 30,
    approach:Param("Approach to use: vis, txt, comb", str) = 'vis'
):
    q_path = Path(q_path)
    cor_path = Path(cor_path)
    cb_path = Path(cb_path)
    vis_path = Path(vis_path)

    q_vid = Video(q_path, fps)
    codebook = pickle.load(open(cb_path, 'rb'))
    simclr = SimCLRModel.load_from_checkpoint(checkpoint_path = str(vis_path)).eval()
    model = SimCLRExtractor(simclr)

    vid_ds = VideoDataset.from_path(cor_path).label_from_paths()
    sorted_rankings = compute_sims(q_vid, vid_ds, model, codebook, 1_000, fps, 5)
    pp = pprint.PrettyPrinter(indent=4)
    pp.pprint(sorted_rankings)